# Generated by Django 5.0.6 on 2024-06-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORSAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='login_id',
            new_name='loginId',
        ),
    ]
